version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: maquinaria_db_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: PasswordSeguro123!
      POSTGRES_DB: maquinaria_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: